### ISSUE TITLE
[RFC] Passing "leftover" props to <video>

### ISSUE THREAD

**Issue by joltmode** [sanity-io/sanity-mux-player#3]
It'd be great if it was possible to add event handlers the React way and any other unthought of or future `<video>` prop.

While I'm at it, it'd be also great if one could attach custom `onClick` handler by merging with the internal `handleClick`.

**Comment by skogsmaskin** [comment]
Yes, this is straight up a front end rendering module parted from our Sanity studio MUX-integration 
code :moon:  It's still on `0.0.24`, but the aim is to be flexible for front end rendering of video. Thanks for posting the first PR @joltmode ! :)
