### ISSUE TITLE
Video muted set to false, still plays mute

### ISSUE THREAD

**Issue by david-j-davis** [sanity-io/sanity-mux-player#9]
Hello, I have a mux component set here: https://github.com/Marmt-Group/client-rock-solid/blob/master/web/src/components/video-player/index.js and a live example of the issue here. Click on the play button, and observe that muted set to false is still playing mute. https://gifted-dijkstra-333b71.netlify.com/
![Screen Shot 2019-12-20 at 5 14 20 PM](https://user-images.githubusercontent.com/3498223/71300699-301e4c00-234c-11ea-8048-3731d93dc6f6.png)

**Comment by david-j-davis** [comment]
So it appears the player does not allow autoplay=true and muted=false, only autoplay=true and muted=false. Why is that, and I wish that wasn't the case...

**Comment by skogsmaskin** [comment]
Hi @david-j-davis. This is a measure for better supporting autoplay. Browsers will not allow autoplay if the sound is not muted (generally - there are some exceptions).

Read more about how Chrome deals with this here: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

I guess we could allow to set both autoplay=true and muted=false, but that would only work in special cases where the user already has deliberately played videos with sound on your site.

**Comment by david-j-davis** [comment]
Thanks for the reply. I guess if this is a matter of best practices then
I'm ok with it as it is and will let my client know.
